name: recruitibase
version: '1.1'
synopsis: A tool for extracting data from a simple YAML "database" of recruiters
description: Over the years I built up a text file of recruiter info to track job hunting efforts. Eventually, I adopted a YAML format for this data to facilitate data extraction. This software does some of that extraction.
license: ISC
author: Dino Morelli
maintainer: dino@ui3.info
copyright: 2018 Dino Morelli
category: Unclassified
extra-source-files:
- package.yaml
- README.md
- recruitibase.yaml
- stack.yaml

github: dino-/recruitibase

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- DeriveGeneric
- OverloadedStrings

dependencies:
- base
- bytestring

library:
  source-dirs: src/lib
  dependencies:
  - aeson
  - containers
  - filepath
  - directory
  - optparse-applicative
  - text
  - yaml

executables:
  recruitibase:
    source-dirs: src/recruitibase
    main: Main.hs
    dependencies:
    - recruitibase

tests:
  recruitibase-test-suite:
    source-dirs: src/test
    main: Main.hs
    dependencies:
    - recruitibase
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
